### ISSUE TITLE
Catwalks do not drop in survival

### ISSUE THREAD

**Issue by mincrmatt12** [TeamDmfMM/Catwalks-4#5]

**Comment by dmf444** [comment]
Fixed in: catwalks-1.12.2-4.0.34.jar

**Comment by rckymtnrfc** [comment]
Classic Ladders are still not dropping when broken in survival.

**Comment by dmf444** [comment]
It does drop. I tested it on my own server in survival.

**Comment by rckymtnrfc** [comment]
Correction.  Classic Ladders break via one punch (by fist) and does not drop.  Breaking with a pickaxe does drop the item.
